[package]
name = "evm-precompile-runtime"
version = "0.1.0"
authors = ["FindoraNetwork"]
edition = "2021"
homepage = "https://findora.org/technology"
repository = "https://github.com/findoranetwork/platform/"
description = "MODEXP precompiles for EVM module."
readme = "README.md"







[dependencies]
evm = { version = "0.33.0", default-features = false, features = ["with-serde"] }
module-evm = { path = "../../../../modules/evm"}
ethereum-types = "0.12"
evm-precompile-basic = { default-features = false, path = "../basic" }
evm-precompile-sha3fips = { default-features = false, path = "../sha3fips" }
evm-precompile-modexp = { default-features = false, path = "../modexp" }
storage = { git = "https://github.com/FindoraNetwork/storage.git", tag = "v0.1.4" }
fp-core = { path = "../../../../primitives/core" }
parking_lot = "0.11.1"